FileVersion = 1

[Project]
Name = "BeefLibrary"
TargetType = "BeefLib"
StartupObject = "BeefLibrary.Program"

[[Project.DistinctOptions]]
Filter = ""

[Configs.Debug.Win64]
BuildKind = "StaticLib"
CLibType = "DynamicDebug"
BeefLibType = "Static"

[Configs.Release.Win64]
BuildKind = "StaticLib"
CLibType = "Dynamic"

[Configs.Paranoid.Win64]
BuildKind = "StaticLib"
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.Win64]
BuildKind = "StaticLib"
CLibType = "Static"
BeefLibType = "Static"
